name: Docker Image CI

on:
  push:
  #   branches: [ "master" ]
  # pull_request:
  #   branches: [ "master" ]
jobs:
  app-ci:
    runs-on: ubuntu-latest
    environment: Production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install App dependencies
        run: |
          # npm install --legacy-peer-deps
          npm i
          ls -la node_modules/
          
      - name: Build App
        run: |
          npm run build

      - name: Test App
        run: |
          npm run test
